[package]
name = "registry"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
serde = "1.0.152"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
aws-config = "0.51.0"
aws-sdk-s3 = "0.21.0"
axum = { version = "0.6.10", features = ["multipart"] }