version: "2"
services:
  s3:
    image: quay.io/minio/minio
    command: server --console-address ":9010" /data
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniominio
    ports:
      - 9000:9000
      - 9010:9010
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3