default interface error {
    enum http-error {
        network,
        timeout,
        invalid-url,
        invalid-request,
        invalid-response
    }

    variant plugin-error {
        http(http-error),
        config-key-not-found(string),
        json(string),
        unexpected(string)
    }
}