interface http {
    record http-request {
        url: string,
        headers: list<tuple<string, string>>
    }

    record http-response {
        status: u16,
        body: list<u8>
    }

    send: func(req: http-request) -> http-response
}

interface config {
    get: func(key: string) -> option<string>
}

interface cache {
    set: func(key: string, value: list<u8>) -> ()
    get: func(key: string) -> option<list<u8>>
}

interface log {
    enum level {
        debug,
        info,
        warn,
        error
    }

    log: func(level: level, msg: string) -> ()
}

interface exports {
   record commit {
      message: string,
      timestamp: u64
  }

  variant enrichment {
      link(string),
      none
  }

  enrich: func(commit: commit) -> result<enrichment, string>
}

default world gitlog {

  import http: self.http
  import config: self.config
  import log: self.log
  import cache: self.cache

  export exports: self.exports

}