interface data {
   use pkg.http.{http-error}

   record commit {
      message: string,
      timestamp: u64
  }

  variant enrichment {
      link(string),
      none
  }

  variant enrichment-error {
    http-error(http-error),
    json-error(string)
  }

  enrich: func(commit: commit) -> result<enrichment, enrichment-error>
}

default world gitlog {

  import http: pkg.http
  import config: pkg.config
  import log: pkg.log
  import cache: pkg.cache

  export data: self.data

}