default interface http {
    use pkg.error.{plugin-error}

    record http-request {
        url: string,
        headers: list<tuple<string, string>>
    }

    record http-response {
        status: u16,
        body: list<u8>
    }

    send: func(req: http-request) -> result<http-response, plugin-error>
}