interface enricher {
    use pkg.commits.{commit}
    use pkg.config.{config-descriptor}
    use pkg.error.{plugin-error}

    record webref {
        label: string,
        link: string
    }

    variant enrichment {
        link(webref),
        tag(string),
        none
    }

    config-discriptors: func() -> list<config-descriptor>
    enrich: func(c: commit) -> result<list<enrichment>, plugin-error>
}

default world plugin-enricher {
  import http: pkg.http
  import config: pkg.config
  import log: pkg.log
  import cache: pkg.cache

  export enricher: self.enricher
}