interface exports {
    record commit {
        message: string,
        timestamp: u64
    }

    variant enrichment {
        link(string),
        none
    }

    enrich: func(commit: commit) -> enrichment
}

world gitlog {
  default export exports
}